CREATE SCHEMA VEHICLES;
-- TRAIN
CREATE TABLE VEHICLES.TRAIN (TRAIN_id varchar(15) PRIMARY KEY, event_id serial, meta jsonb, search jsonb, domain jsonb);
CREATE INDEX TRAIN_META on VEHICLES.TRAIN USING gin(meta);
CREATE INDEX TRAIN_DOMAIN on VEHICLES.TRAIN USING gin(domain);
CREATE INDEX TRAIN_SEARCH on VEHICLES.TRAIN USING gin(search);

-- CAR
CREATE TABLE VEHICLES.CAR (CAR_id varchar(15) PRIMARY KEY, event_id serial, meta jsonb, search jsonb, domain jsonb);
CREATE INDEX CAR_META on VEHICLES.CAR USING gin(meta);
CREATE INDEX CAR_DOMAIN on VEHICLES.CAR USING gin(domain);
CREATE INDEX CAR_SEARCH on VEHICLES.CAR USING gin(search);
